### ISSUE TITLE
Image flipped on video play back

### ISSUE THREAD

**Issue by Urthstripe29** [Affectiva/affdexme-android#19]
I noticed when running the demo the video is flipped. Note the headphone cable on the right on the original video file but on the left in the application. I tested this with another video and the output is flipped there too. Very noticeable with a video that has text in it. I don't think this is an SDK issue but rather unexpected behavior in the sample application.

Best guess it that you are checking for front camera without taking in account it is a video. By default self.cameraToUse is set to AFDX_CAMERA_FRONT in viewDidLoad.

```
        // flip image if the front camera is being used so that the perspective is mirrored.
        if (self.cameraToUse == AFDX_CAMERA_FRONT) {
            UIImage *flippedImage = [UIImage imageWithCGImage:newImage.CGImage
                                                        scale:image.scale
                                                  orientation:UIImageOrientationUpMirrored];
            [weakSelf.imageView setImage:flippedImage];
        } else {
            [weakSelf.imageView setImage:newImage];
        }
```

![screenshot 2016-06-21 16 21 14](https://cloud.githubusercontent.com/assets/10824143/16247265/930860de-37ce-11e6-8fea-c3d5080a974e.png)

**Comment by Urthstripe29** [comment]
Setting a breakpoint on line 512 shows that it is flipping it here which I imagine is unintended.

![screenshot 2016-06-21 16 45 09](https://cloud.githubusercontent.com/assets/10824143/16247561/e96f1c96-37cf-11e6-9883-4f2a5fc45452.png)

**Comment by adennie** [comment]
I think you meant to log this issue for https://github.com/Affectiva/affdexme-ios...

**Comment by Urthstripe29** [comment]
Lol thanks you are correct
