### ISSUE TITLE
java.lang.IllegalStateException: Camera is unavailable. Please close the app that is using the camera and then try again.

### ISSUE THREAD

**Issue by Ornolfr** [Affectiva/affdexme-android#27]
I'm using 2 different activities where I use the `CameraDetector`. Both activities start the face recognition after `onStart` and stop it before `onStop`. But when I open the second activity from the first one it seems that the first one is still using the camera thus throwing the exception. What should I do? I can't find any method to release camera in your SDK! Thanks in advance.

**Comment by Ornolfr** [comment]
Managed to fix this by moving the start/stop methods to `onResume` and `onPause` respectively.

**Comment by adennie** [comment]
Seems like you already figured this out, but for anybody else coming along later, here's the story: when starting Activity B from Activity A, B's onStart() is called before A's onStop(), so the Camera instance used by the CameraDetector in A was still alive when B tried to create another one referencing the same hardware camera, which is not allowed.
